export { Header } from "./Header";
export { About } from "./About";
export { Explore } from "./Explore";
export { Classes } from "./Classes";
export { Infos } from "./Infos";
export { Team } from "./Team";
export { Plans } from "./Plans";
export { Schedule } from "./Schedule";
export { Footer } from "./Footer";